function [D,W,error] = distance_sa(X)
% This function takes a set of parameters and returns the distance between
% the moments in the data and the moments generated by the parameter set.

tic

%read in parameter names from the X vector
scale_h    =  X(3);
bmg        =  .5;
bsdg       =  .5;
lnF        =  scale_h + log(X(1));
delta      =  X(2);
scale_f    =  scale_h + log(X(4));
beta       =  X(5);
bmh        =  X(6);
bsdh       =  X(7);
L_p        =  X(8);
L_z        =  X(9);
L_b        =  X(10);
alp        =  0;
gam        =  X(11)/beta;
cs         =  X(12);

main_sa;  %this is the main program (to run simulation, generate moments, etc)

%% Targets

vtranData     = [0.618; 0.321; 0.048; 0.013; 0.271; 0.375; 0.241; 0.113]; %This is chance of moving [1->0;1->1;1->2;1->>=3,2->0;2->1;2->2;2->>=3]
mhazData      = [0.694; 0.515; 0.450; 0.424;.389]; %Probability of match dying conditional on surviving 0,1,2,3,4 year
clidistData   = [-2.0703; 0.1098];  %coefficient and rMSE on clidist regression
mstatData     = [9.326 + log(62.964); 8.514 + log(62.964); 1.658; 2.281]; %mean log domestic sales, mean log exports, standard dev ds, standard dev exp, originally calculated in thousands of 1977 pesos, converted to 1992 dollars by multiplying by 62.964 
mnumexData    = [0.709; 0.383; 0.300; 0.263; 0.293]; % 1-5yr old cohort membership separation hazards%
mavexData     = [11.1814; 12.3396; 12.64526; 12.75636; 12.8401]; % log average sales per exporter by cohort
mavshipData   = 4.824; % dropping top 5%, average number of shipments per year per client via CJ's email of 6-9-2012 
mregData      = [2.677;-0.143;2.180]; %ncoefficients from reg of log(sales per client) on log no. of clients, (log no. of clients)^2, and root MSE
mexregData    = [4.093+(1-0.408)*log(62.964);0.408;2.097]; %regression of log export sales on log home sales, constant,log(exp),and root MSE, only need to adjust constant for exchange rate
mexshrData    = 0.164; %share of firms which export

%% Weights

%standard errors (see moments folder for details of calculations)
vtranSE     = [0.0025; 0.0024; 0.0011; 0.0006; 0.0071; 0.0066; 0.0059; 0.0043];
mhazSE      = [0.00230; 0.00484; 0.00674; 0.00865; 0.01066]; 
clidistSE   = [0.0228;sqrt(2)*0.1098^2/sqrt(36)];   % [0.00230; 0.002842]
mstatSE     = [1.658/sqrt(14759); 2.281/sqrt(2436); sqrt(2)*1.658^2/sqrt(14758); sqrt(2)*2.281^2/sqrt(2435)];
mnumexSE    = [0.00287; 0.00569; 0.00683; 0.00784;0.00861]; 
mavexSE     = [1.681/sqrt(10995); 1.733/sqrt(4644); 1.742/sqrt(2909); 2.412/sqrt(2100);1.749/sqrt(1564)];
mavshipSE   = 7.142/sqrt(67432); % via CJ's email of 6-7-2012, total number of pairs is from CJ's email of 5-17-2012.
mregSE      = [0.15195;0.09592;sqrt(2)*2.180^2/sqrt(6618)]; 
mexregSE    = [sqrt(.0218^2*log(62.964)^2+.0218^2*2*log(62.964)*9.326+.2357^2);0.0218;sqrt(2)*2.097^2/sqrt(2359)]; 
mexshrSE    = 0.0030;

Data = cat(1,vtranData,mhazData,clidistData,mstatData,mnumexData,mavshipData,mavexData,mregData,mexregData,mexshrData);

W = zeros(size(Data,1));
W(1:size(Data,1)+1:end) = (1./cat(1,vtranSE,mhazSE,clidistSE,mstatSE,mnumexSE,mavshipSE,mavexSE,mregSE,mexregSE,mexshrSE)).^2;

%% Realizations

% Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavship,mavex,mreg,mexreg,mexshr);
Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavship,mavex,mreg,mexreg,mexshr);

error = Data-Model;

D = error'*W*error;

nanflag = isnan(D); 
if nanflag>0;
        D = D * 10; 
    end

    punishment
    D = D*(1+punishment);

    display('vtran(8),mhaz(5),clidist(2),mstat(4),mnumex(5),mavex(5),mavship(1),mreg(3),mexreg(3),mexshr(1)');
    mmm = cat(2,Data,Model)
    X %print out current parameter guess
    D

    %Old D report
    Old_D = norm(error)/norm(Data)

    last_loop_run_time = toc/60

    fid = fopen('9-4-2012.log','a');
    fprintf(fid,'moments\n\n');
    fprintf(fid,'%f  %f\n',mmm');
    fprintf(fid,'params\n');
    fprintf(fid,'%f\n',X');
    fprintf(fid,'distance\n');
    fprintf(fid,'%f\n',D);
    fprintf(fid,'%f\n',Old_D);
    fprintf(fid,'run time\n');
    fprintf(fid,'%f\n',last_loop_run_time);

end
