function [D,W,error] = distance_mc(X,moments)
% This function takes a set of parameters and returns the distance between
% the moments in the data and the moments generated by the parameter set.

rng(80085);


tic

format long;

%read in parameter names from the X vector
scale_h    =  X(3);
ag         =  .5;
bg         =  .5;
lnF        =  scale_h + log(X(1));
delta      =  X(2);
scale_f    =  scale_h + log(X(4));
beta       =  X(5);
ah         =  X(6);
bh         =  X(7);
L_p        =  0; %zero would require changing the value function solver...
D_p        =  0;
L_z        =  X(8);
D_z        =  X(9);
L_b        =  X(10);
alp        =  0;
gam        =  X(11)*(1+beta)/beta;
cs         =  X(12);
sig_p      =  X(13);

main_noprod;  %this is the main program (to run simulation, generate moments, etc)

%% Targets

vtranData     = [0.618; 0.321; 0.048; 0.013; 0.271; 0.375; 0.241; 0.113]; %Taken from CJ_cohorts_6-15-2012.pdf in S://moments
mhazData      = [0.694; 0.515; 0.450; 0.424;.389]; %Taken from CJ_cohorts_6-15-2012.pdf in S://moments
clidistData   = [-2.0703; 0.1098];  %Taken from file "Copy of client distribution regression.xslx" in S://moments
mstatData     = [12.257;2.281]; %Taken from CJ_cohorts_6-15-2012.pdf in S://moments, and old data
mnumexData    = [0.709; 0.383; 0.300; 0.263; 0.293]; %Taken from CJ_cohorts_6-15-2012.pdf in S://moments
mavexData     = [11.1814; 12.3396; 12.64526; 12.75636; 12.8401]; % Taken from CJ_cohorts_6-15-2012.pdf in S://moments
mavshipData   = 4.824; % dropping top 5%, average number of shipments per year per client via CJ's email of 6-9-2012
mregData      = [2.677;-0.143;2.180]; %ncoefficients from reg of log(sales per client) on log no. of clients, (log no. of clients)^2, and root MSE, from file "EINS as IDs results2.docx" in CJ's email of 6-11-2012
mexregData    = [1.383+(1-0.744)*log(0.303);0.744;2.127]; % from eam_moms_out.log file in Marcela's email of 9-24-2012, with adjustment of constant for exchange rate (constant originally in thousands of 2009 pesos, converted to 1992 dollars)
mexshrData    = 0.318; %share of firms which export from eam_moms_out.log file in Marcela's email of 9-24-2012
mlageregData  = [0.8484;1.3891]; %regression coefficient and MSE of log exports on log lagged exports 
mlagdregData  = [0.9864;0.4093]; %regression coefficient and MSE of log dom sales on log lagged dom sales 

%% Weights

%standard errors (see moments folder for details of calculations)
vtranSE     = [0.0025; 0.0024; 0.0011; 0.0006; 0.0071; 0.0066; 0.0059; 0.0043]; %Calculated from CJ_cohorts_6-15-2012.pdf in S://moments
mhazSE      = [0.00230; 0.00484; 0.00674; 0.00865; 0.01066]; %Calculated from CJ_cohorts_6-15-2012.pdf in S://moments
clidistSE   = [0.0228;sqrt(2)*0.1098^2/sqrt(36)]; %Calculated from file "Copy of client distribution regression.xslx" in S://moments
mstatSE     = [2.107/sqrt(48133);sqrt(2)*2.197^2/sqrt(48133)]; %all calculated from CJ's email of 12-18-2012.
mnumexSE    = [0.00287; 0.00569; 0.00683; 0.00784;0.00861]; %Calculated from CJ_cohorts_6-15-2012.pdf in S://moments
mavexSE     = [1.681/sqrt(10995); 1.733/sqrt(4644); 1.742/sqrt(2909); 2.412/sqrt(2100);1.749/sqrt(1564)]; %??
mavshipSE   = 7.142/sqrt(67432); % via CJ's email of 6-7-2012, total number of pairs is from CJ's email of 5-17-2012.
mregSE      = [0.15195;0.09592;sqrt(2)*2.180^2/sqrt(6618)];  % Calculated from from file "EINS as IDs results2.docx" in CJ's email of 6-11-2012
mexregSE    = [sqrt(0.0065^2+(log(0.303))^2 * 0.1018^2 - log(0.303) * 2.127^2/(15.66262*34330));0.0065;sqrt(2)*2.127^2/sqrt(34330)]; % calculated from eam_moms_out.log file in Marcela's email of 9-24-2012
mexshrSE    = 0.466/sqrt(115334); % calculated from eam_moms_out.log file in Marcela's email of 9-24-2012
%mlagsregSE  = 0.00367/sqrt(20223); % calculated from in-house transactions data, .do file/log is in S: moments folder.
mlageregSE  = [0.00367;sqrt(2)*1.3891^2/sqrt(20223)]; %regression coefficient and MSE of log exports on log lagged exports, in-house transactions 
mlagdregSE  = [0.0010238;sqrt(2)*0.40926^2/sqrt(50262)]; %regression coefficient and MSE of log dom sales on log lagged dom sales, in-house 80's colombia 

%Data = cat(1,vtranData,mhazData,clidistData,mstatData,mnumexData,mavshipData,mavexData,mregData,mexregData,mexshrData,mlageregData,mlagdregData);
Data = moments;

W = zeros(size(Data,1));
W(1:size(Data,1)+1:end) = (1./cat(1,vtranSE,mhazSE,clidistSE,mstatSE,mnumexSE,mavshipSE,mavexSE,mregSE,mexregSE,mexshrSE,mlageregSE,mlagdregSE)).^2;

%% Realizations

% Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavship,mavex,mreg,mexreg,mexshr);
Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavship,mavex,mreg,mexreg,mexshr,mlagereg,mlagdreg);

error = Data-Model;

D = error'*W*error;

nanflag = isnan(D); 
if nanflag>0;
        D = D * 10; 
end

    punishment
    D = D*(1+punishment);
    
    mmm = cat(2,Data,Model)
    X %print out current parameter guess
    D

    %Old D report
    Old_D = norm(error)/norm(Data)

    last_loop_run_time = toc/60

end
