function D = distance(X,shk)
% This function takes a set of parameters and returns the distance between
% the moments in the data and the moments generated by the parameter set.

%last updated 2011/8/23 by David Jinkins

tic


shk = struct(); 
 
%read in errors
load data/srates.mat
load data/eps.mat
load data/drw.mat 

shk.yy0 = yy0; shk.yy1=yy1; shk.yy2=yy2; shk.sp_h=sp_h; shk.sp_f=sp_f; shk.sp_p_uni=sp_p_uni; shk.ud_h=ud_h; shk.ud_p=ud_p; shk.ud_f=ud_f;
shk.drw1=drw1; shk.drw2=drw2; shk.drw3=drw3; shk.drw4=drw4; shk.drw5=drw5; shk.drw6=drw6; shk.drw7=drw7; shk.drw8=drw8; shk.drw9=drw9; 
shk.drw10=drw10; shk.drw11=drw11; shk.drw12=drw12;


% scale_h    =  12.9324;
% ag        =  0.1180;
% bg        =  1.3315;
% lnF        =  scale_h + log(0.4037);
% delta      =  0.6645;
% scale_f    =  scale_h + log(1.2935);
% beta        =  1.9725;
% ah         =  1.7008;
% bh         =  .3263;
% L_p        =  .7736;
% L_z        =  .6222;
% L_b        =  1.8153;
% alp        =  .7641;
% gam        =  1.1099;

scale_h    =  10.0016;
ag        =  0.6525;
bg        =  0.0277;
lnF        =  scale_h + log(0.2247);
delta      =  0.5054;
scale_f    =  scale_h + log(.5729);
beta        =  .6595;
ah         =  0.3268;
bh         =  .3353;
L_p        =  .5647;
L_z        =  .9264;
L_b        =  1.9910;
alp        =  .9905;
gam        =  0;

%read in parameter names from the X vector
% scale_h    =  11.8634;
% ag        =  0.1271;
% bg        =  0.4415;
% lnF        =  scale_h + log(0.4676);
% delta      =  0.4872;
% scale_f    =  scale_h + log(1.8240);
% beta        =  .1893;
% ah         =  0.8132;
% bh         =  .4320;
% L_p        =  .8057;
% L_z        =  .9787;
% L_b        =  2.4605;
% alp        =  .1118;
% gam        =  .3993;

%display(X);

main2;  %this is the main program (to run simulation, generate moments, etc)

%% Targets


vtranData     = [0.614; 0.332; 0.043; 0.011; 0.262; 0.375; 0.249; 0.115]; %This is chance of moving [1->0;1->1;1->2;1->>3,2->0;2->1;2->2;2->>3]
mhazData      = [0.713; 0.378; 0.289; 0.281; 0.217]; %Probability of match dying conditional on surviving 1,2,3,4 and 5 years
clidistData   = [.843; .100; .057];  %percentage of firms with 1,2,3,4, and 5 clients
mstatData     = [0.1870; 0.366; 0.4947; 0.3045]; %aggregate stats, see moms.m for specifics
mnumexData    = [0.507; 0.441; 0.422; 0.390]; % 2-5 yr old cohort membership relative to one year olds year
mavexData     = [0.312; 0.237; 0.217; 0.191]; % 2-5 yr. old inverse sales per exporter x first year sales per exporter
mavshipData   = [1/8;1/8;4/8;14/100;53/100]; %[10%,25%,50%,75%,90%] percentile of number of shipments per year divided by 8 and 100 
mregData      = [.558;-0.00589*(-100);3.493*(1/5)]; %normalized coefficients from reg of log(sales per client) on no. of clients, no. of clients^2, and MSE, from file reg2 lsales = #buyers.docx in cj_table_and_moment_data folder

Data = cat(1,vtranData,mhazData,clidistData,mstatData,mnumexData,mavexData,mavshipData,mregData);
%% Realizations

Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavex,mavship,mreg);
   
    D = norm(Data-Model)/norm(Data);
    D_report = D;
    
    nanflag = isnan(D); 
    if nanflag>0;
        D = 100; 
    end
    
    display('vtran(8),mhaz(5),clidist(3),mstat(4),mnumex(4),mavex(4),mavship(5),mreg(3)'); 
    mmm = cat(2,Data,Model)
    X %print out current parameter guess
    D_report


toc
end
