function [D,W,error] = distance(X,fakemoments)
% This function takes a set of parameters and returns the distance between
% the moments in the data and the moments generated by the parameter set.

tic

%read in parameter names from the X vector
scale_h    =  X(5);
bmg        =  X(1);
bsdg       =  X(2);
lnF        =  scale_h + log(X(3));
delta      =  X(4);
scale_f    =  scale_h + log(X(6));
beta       =  X(7);
bmh        =  X(8);
bsdh       =  X(9);
L_p        =  X(10);
L_z        =  X(11);
L_b        =  X(12);
alp        =  X(13);
gam        =  X(14)/beta;
cs         =  X(15);

main;  %this is the main program (to run simulation, generate moments, etc)

%% Targets

vtranData     = fakemoments(1:8);
mhazData      = fakemoments(9:13);
clidistData   = fakemoments(14:15);
mstatData     = fakemoments(16:19);
mnumexData    = fakemoments(20:24);
mavshipData   = fakemoments(25);
mavexData     = fakemoments(26:30);
mregData      = fakemoments(31:33);
mexregData    = fakemoments(34:36);
mexshrData    = fakemoments(37);

%% Weights

%standard errors (see moments folder for details of calculations)
vtranSE     = [0.0025; 0.0024; 0.0011; 0.0006; 0.0071; 0.0066; 0.0059; 0.0043];
mhazSE      = [0.00230; 0.00484; 0.00674; 0.00865; 0.01066]; 
clidistSE   = [0.0228;sqrt(2)*0.1098^2/sqrt(36)];   % [0.00230; 0.002842]
mstatSE     = [1.658/sqrt(14759); 2.281/sqrt(2436); sqrt(2)*1.658^2/sqrt(14758); sqrt(2)*2.281^2/sqrt(2435)];
mnumexSE    = [0.00287; 0.00569; 0.00683; 0.00784;0.00861]; 
mavexSE     = [1.681/sqrt(10995); 1.733/sqrt(4644); 1.742/sqrt(2909); 2.412/sqrt(2100);1.749/sqrt(1564)];
mavshipSE   = 7.142/sqrt(67432); % via CJ's email of 6-7-2012, total number of pairs is from CJ's email of 5-17-2012.
mregSE      = [0.15195;0.09592;sqrt(2)*2.180^2/sqrt(6618)]; 
mexregSE    = [sqrt(.0218^2*log(62.964)^2+.0218^2*2*log(62.964)*9.326+.2357^2);0.0218;sqrt(2)*2.097^2/sqrt(2359)]; 
mexshrSE    = 0.0030;

Data = cat(1,vtranData,mhazData,clidistData,mstatData,mnumexData,mavshipData,mavexData,mregData,mexregData,mexshrData);

W = zeros(size(Data,1));
W(1:size(Data,1)+1:end) = (1./cat(1,vtranSE,mhazSE,clidistSE,mstatSE,mnumexSE,mavshipSE,mavexSE,mregSE,mexregSE,mexshrSE)).^2;

%% Realizations

% Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavship,mavex,mreg,mexreg,mexshr);
Model = cat(1,vtran,hazrate,clidist,mstat,mnumex,mavship,mavex,mreg,mexreg,mexshr);

error = Data-Model;

D = error'*W*error;

nanflag = isnan(D); 
if nanflag>0;
        D = D * 10; 
    end

    punishment
    D = D*(1+punishment);

    display('vtran(8),mhaz(5),clidist(2),mstat(4),mnumex(5),mavex(5),mavship(1),mreg(3),mexreg(3),mexshr(1)');
    mmm = cat(2,Data,Model)
    X %print out current parameter guess
    D

    %Old D report
    Old_D = norm(error)/norm(Data)

    last_loop_run_time = toc/60

    fid = fopen('8-06-2012.log','a');
    fprintf(fid,'moments\n\n');
    fprintf(fid,'%f  %f\n',mmm');
    fprintf(fid,'params\n');
    fprintf(fid,'%f\n',X');
    fprintf(fid,'distance\n');
    fprintf(fid,'%f\n',D);
    fprintf(fid,'%f\n',Old_D);
    fprintf(fid,'run time\n');
    fprintf(fid,'%f\n',last_loop_run_time);

end
